name: coffe_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.4.1
  onesignal_flutter: ^3.2.9
  http: ^1.2.2
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  flutter_paymob: ^1.0.5
  flutter_inappwebview: ^6.1.5
  dotted_line: ^3.2.3
  introduction_screen: ^3.1.14
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0




flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/Rectangle 1.svg
    - assets/onboarding_imgs/
    - assets/onboarding_imgs/
    - assets/onboarding_imgs/unsplash_SCbq6uKCyMY.png
    - assets/images/app_img.png

  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf


