name: coffe_app
description: "A new Flutter project."
flutter_native_splash:
  color: "#ffffff"
  image: assets/onboarding_imgs/Frame 2.png
  android: true
  ios: true
  android_12:
    image: assets/onboarding_imgs/Frame 2.png
    icon_background_color: "#ffffff"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_animate: ^4.5.2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.4.1
  onesignal_flutter: ^3.2.9
  http: ^1.2.2
  intl: ^0.19.0
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  flutter_paymob: ^1.0.5
  google_sign_in: ^6.2.2
  dotted_line: ^3.2.3
  introduction_screen: ^3.1.14
  shared_preferences: ^2.5.1
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.10
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.4
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0




flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/Rectangle 1.svg
    - assets/onboarding_imgs/
    - assets/onboarding_imgs/unsplash_SCbq6uKCyMY.png
    - assets/images/app_img.png
    - assets/onboarding_imgs/Frame 2.png

  fonts:
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf


